services:
  - type: web
    name: leetcode-30-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_BACKUP_REPO
        value: alidin000/leetcode-30-bot
      - key: GITHUB_BACKUP_BRANCH
        value: data-backup
      - key: GITHUB_BACKUP_PATH
        value: data/backup.json
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: leetcode-30-bot
          property: host
      - key: CHALLENGE_START_DATE
        value: 2026-10-06
      - key: TIMEZONE
        value: Europe/Budapest
      - key: DB_PATH
        value: leetcode30.db
